### ISSUE TITLE
Failed to send authorized request / header parser received no bytes

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/conformance-test-harness#155] opened 2021-12-25 09:52 UTC
We recently started having a conformance suite test failure within the CSS CI, which seems to be a harness bug: https://github.com/solid/community-server/runs/4630611541?check_suite_focus=true#step:9:259

```
>>> failed features:
js failed:
>>>>
01: clients.alice.sendAuthorized('DAHU', resource.url, null, null)
<<<<
org.graalvm.polyglot.PolyglotException: org.solid.testharness.api.TestHarnessException: Failed to send authorized request
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
- org.solid.testharness.api.SolidClient.sendAuthorized(SolidClient.java:104)
- <js>.:program(Unnamed:1)

../data/web-access-control/protected-operation/read-resource-access-R.feature:56
<<<
```

**Comment by kjetilk** [comment] 2021-12-25 23:45
We're on the case, but expect no resolution in a while due to holidays.

It appears to be a problem with HTTP/2 vs HTTP/1.1, it may be the test harness client not quite detecting the distinction.

**Comment by kjetilk** [comment] 2021-12-25 23:57
See https://github.com/solid/specification-tests/pull/60 for more on this.

**Comment by edwardsph** [comment] 2022-01-11 14:44
@RubenVerborgh This was tricky to diagnose. It looked as though the response was incomplete, suggesting the connection from CSS was being closed before the output buffer was flushed. However, I have not been able to reproduce that condition in any other way so instead I had to conclude there is a bug in the JDK similar to https://bugs.openjdk.java.net/browse/JDK-8239117. As a workaround, I am making the client retry the request and we now get a response:
```
  < HTTP_1_1 400
  < connection: close
```
The fix will be released along with other changes by the end of the week but I think we will still see the test failing for another reason - I'm not convinced 400 is the right response. Can you look at the discussion here to see why I think it must be 405 or 501: https://gitter.im/solid/specification?at=61dc64685dc6213cd4d52145

**Comment by RubenVerborgh** [comment] 2022-01-11 15:55
Agree, if it's a non-supported method, it should be `405` CC @joachimvh

**Comment by edwardsph** [comment] 2022-01-11 16:19
Thanks - and just to flag that it then needs to include an Accept header as per https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.6

**Closed** 2022-01-13 08:33 UTC
Labels: bug

**Comment by joachimvh** [comment] 2022-01-14 09:53
> I'm not convinced 400 is the right response. Can you look at the discussion here to see why I think it must be 405 or 501: https://gitter.im/solid/specification?at=61dc64685dc6213cd4d52145

Apparently Node.js has hardcoded which HTTP methods it supports, in case a method is not in the fixed list our server will never even see the request. Here is their argumentation on why they return 400 instead of 105: https://github.com/nodejs/node/issues/17248#issuecomment-346360466. This probably also explains why you got a different kind of response here.

This means it's pretty much impossible for us to return a 405 in those cases. We can do it in case of unsupported methods that do exist, e.g. PURGE.

**Comment by RubenVerborgh** [comment] 2022-01-14 10:03
Actually, @edwardsph, I believe testing this is out of scope for Solid.
The Solid specs do not govern the `DAHU` method.

**Comment by edwardsph** [comment] 2022-01-14 10:10
Agreed - unknown methods are covered by the HTTP spec so testing methods like DAHU is probably out of scope though it is interesting to see how different servers respond.
The Solid spec mentions the 405 response but since that is also in line with the HTTP spec I'm not sure the requirement is needed at all. If the spec keeps this requirement we should still test for 405 responses I think.
I've suggested to @joachimvh that 405 is still a better response than 501 for unsupported methods but he was already looking at that.

**Comment by kjetilk** [comment] 2022-01-14 10:23
I think there is a more general problem here: There seems to be tension when we're trying to close the world. Whenever we're just specifying an open world, it is easy to test, but not very interesting, because you can only test the good path. The open world has quite a lot of affordances, you can in principle respond to every request with a 405, "you're not allowed to do anything here", or a 501, "it's OK to ask, but no" but closed world is interesting because it allows to test things that shouldn't happen, because they may have harmful effects.

I can go with `400` in this case (although I agree with some of the commenters there that Node should not make that decision). I think it is important to close the world in situations where the user may be exposed to manipulation, but in this case, it should suffice that the server does not change the state of the target resource and sends an error, which is kinda trivial, and yet, what I wanted to test.

**Comment by edwardsph** [comment] 2022-01-14 10:24
As an aside wrt. Node - If Solid adopts the proposed HTTP method `QUERY` this would present a problem for Node based servers, we would be waiting for the method to be registered in IANA and added to the HTTP1.1 parser in Node (or have to replace the parser as proposed in the issue referenced above). I find it odd that the HTTP2 parser in Node behaves differently - it undermines the arguments for the choice made in the HTTP1.1. parser.

**Comment by csarven** [comment] 2022-01-14 10:30
As mentioned in Gitter and RFC, for an unrecognised method, 501 would be most appropriate. A server may recognise DAHU, but a Solid server is not expected to recognise it, hence 501 is appropriate. Just because Solid Protocol doesn't call out 501, it doesn't rule out appropriate responses as per RFC.

Even still, a server could respond to DAHU with 405 irrespective to genuinely recognising it or not - there is no sure way to tell. The Solid Protocol grants that possibility. Both 501 and 405 are clear about the issue with respect to the HTTP method.

If devs want to ignore available 501, 405.. and make an argument for 400 / equate with 4xx - all purpose code - then at least make the effort to provide a message in the response body explaining what went wrong.

From the point of testing, 501, 405, and with some cringing, 400 is okay. From the point of a server, I think they should aim for 501, 405, 400 (in that order) - Solid server or not.

**Comment by RubenVerborgh** [comment] 2022-01-14 10:59
> Just because Solid Protocol doesn't call out 501, it doesn't rule out appropriate responses as per RFC.

My point is rather: that's up to an RFC2616 test. It's not specific to Solid. So we shouldn't test it.

> you can only test the good path

That's not correct IMHO: we can test good and bad Solid paths. Just not (good or bad) non-Solid paths.

**Comment by kjetilk** [comment] 2022-01-14 11:25
> That's not correct IMHO: we can test good and bad Solid paths. Just not (good or bad) non-Solid paths.

Sure, but there really isn't a lot of bad Solid paths left with the way that we're formulated the spec... It makes me concerned for the overall health of the ecosystem.

**Comment by csarven** [comment] 2022-01-14 11:26
I don't have a strong opinion on whether to include a test for DAHU or not. Or perhaps more broadly, whether to test RFC 7231 conformance or not. The thing is, if only the requirements listed in the Solid Protocol are tested, it is possible to pass it with flying colours but not necessarily be a conforming HTTP server. The Solid Protocol calls for the RFC requirements, so I think the question is more about whether the respective tests are imported or not.

**Comment by kjetilk** [comment] 2022-01-14 11:28
Yeah, it seems to be rather in conflict with the gist of https://github.com/solid/specification/issues/288

**Comment by kjetilk** [comment] 2022-01-14 11:47
I tend to be OK with us not formulating a lot of HTTP requirements in the spec, but when it comes to testing, I think it is very important to be helpful and have tests for an authoritative understanding of underlying specs. 

As I said in spec#288, pragmatically, a developer should be able to go with their intuition and be confident that if their intuition is wrong, they will fail a test, and then they can discover an authoritative answer by inspecting the test (which we are very conscious about making easy). Or they can suggest a change. If we don't specify anything/much from HTTP and also have no tests because we don't have references to attach it to, then we are being very unhelpful.

We are already going in a rather different direction that I would like to, since we don't encode a lot of the understanding in tests, and so we're not being terribly helpful already. I would not want to take it even further in that direction.

We could of course make a "Solid Authoritative HTTP test suite" separate from the protocol test suite. That might actually be a good idea.

**Comment by RubenVerborgh** [comment] 2022-01-14 12:01
> We could of course make a "Solid Authoritative HTTP test suite" separate from the protocol test suite. That might actually be a good idea.

+1
-- 
This e-mail, and any attachments thereto, is intended only for use by the 
addressee(s) named herein and may contain legally privileged, confidential 
and/or proprietary information. If you are not the intended recipient of 
this e-mail (or the person responsible for delivering this document to the 
intended recipient), please do not disseminate, distribute, print or copy 
this e-mail, or any attachment thereto. If you have received this e-mail in 
error, please respond to the individual sending the message, and 
permanently delete the email.
